### ISSUE TITLE
Tracking issue: Emoji

### ISSUE THREAD

**Issue by goto-bus-stop** [u-wave/web#2150]
A semi-ordered todo list for improving emoji support in üWave.

- [x] ship twitter emoji https://github.com/u-wave/web/pull/2149
- [ ] parse unicode emoji, not just shortcodes
- [ ] support skin tone as modifiers, instead of the `_toneX` emoji suffixes
- [ ] client setting to pick default skin tone
- [ ] maybe use a slack-like emoji picker? at least something that only shows the images and not the names too
- [x] static custom emoji (#2515)
- [x] runtime-updatable third-party emotes (#2669)
- [ ] runtime-updatable custom emoji (w/ local upload, like slack or discord)
- [ ] stretch: is it worth having a discord/slack-like visual input?
    ![image](https://user-images.githubusercontent.com/1006268/141756049-61abde4a-4bdb-45f1-a70f-6de362680ec7.png)
